import { VOICE_MODELS } from '../../../src/voice/voiceCost.js';

// Sourced from the shared voice-model registry so the client's cost estimate
// can never be computed against a different model than the session runs on.
const GEMINI_REALTIME_MODEL_DEFAULT = VOICE_MODELS.standard.id;

const GEMINI_REALTIME_MODEL_MINI_DEFAULT = VOICE_MODELS.mini.id;

const GEMINI_REALTIME_VOICE_DEFAULT = 'Puck';

const GEMINI_REALTIME_REASONING_DEFAULT = 'low';

const GEMINI_REALTIME_CONTEXT_TOKENS_DEFAULT = 3000;

const GEMINI_REALTIME_CONTEXT_RETENTION_DEFAULT = 0.5;

const GEMINI_HUD_SUMMARY_MODEL_DEFAULT = 'gemini-2.0-flash-lite';

export {
  GEMINI_HUD_SUMMARY_MODEL_DEFAULT,
  GEMINI_REALTIME_MODEL_MINI_DEFAULT,
  GEMINI_REALTIME_MODEL_DEFAULT,
  GEMINI_REALTIME_VOICE_DEFAULT,
  GEMINI_REALTIME_REASONING_DEFAULT,
  GEMINI_REALTIME_CONTEXT_TOKENS_DEFAULT,
  GEMINI_REALTIME_CONTEXT_RETENTION_DEFAULT,
};
